# Generated by Django 3.2.7 on 2021-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210929_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('youtube', models.URLField(null=True)),
            ],
        ),
    ]
