# Generated by Django 3.2.7 on 2021-09-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_connected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connected',
            options={'verbose_name': 'connected', 'verbose_name_plural': 'connected accounts'},
        ),
    ]
