# Generated by Django 3.2.7 on 2021-09-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('youtube', models.URLField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'connected',
                'verbose_name_plural': 'connected accounts',
            },
        ),
    ]
