# Generated by Django 3.2.7 on 2021-09-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connected',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='users.profile'),
        ),
    ]
